import { Category, OnboardingSlide, Pose } from '@/types/types';

export const categories: Category[] = [
  {
    id: 'women',
    name: 'Women',
    imageUrl: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg',
    count: 20,
  },
  {
    id: 'men',
    name: 'Men',
    imageUrl: 'https://images.pexels.com/photos/3785104/pexels-photo-3785104.jpeg',
    count: 20,
  },
  {
    id: 'kids',
    name: 'Kids',
    imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
    count: 20,
  },
  {
    id: 'couples',
    name: 'Couples',
    imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
    count: 20,
  },
  {
    id: 'dogs',
    name: 'Dogs',
    imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
    count: 20,
  },
  {
    id: 'cats',
    name: 'Cats',
    imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
    count: 20,
  },
];

export const onboardingSlides: OnboardingSlide[] = [
  {
    id: '1',
    title: 'Discover Perfect Poses',
    description:
      'Browse thousands of professional poses for every occasion and subject',
    imageUrl: 'https://images.pexels.com/photos/3785104/pexels-photo-3785104.jpeg',
  },
  {
    id: '2',
    title: 'Save Your Favorites',
    description:
      'Create your personal collection of poses for quick access anytime',
    imageUrl: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg',
  },
  {
    id: '3',
    title: 'AI-Powered Tools',
    description:
      'Transform your photos with background changes, outfit try-on, and pose transfer',
    imageUrl: 'https://images.pexels.com/photos/3861458/pexels-photo-3861458.jpeg',
  },
  {
    id: '4',
    title: 'Start Creating',
    description: 'Get inspired and capture amazing photos with PoseStudio',
    imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
  },
];

export const poses: Record<string, Pose[]> = {
  women: [
    {
      id: 'w1',
      title: 'Casual Standing',
      description: 'Relaxed standing pose with natural body position',
      imageUrl: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w2',
      title: 'Side Profile',
      description: 'Elegant side profile with head turned',
      imageUrl: 'https://images.pexels.com/photos/3756523/pexels-photo-3756523.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w3',
      title: 'Seated Elegance',
      description: 'Graceful seated pose with crossed legs',
      imageUrl: 'https://images.pexels.com/photos/3775087/pexels-photo-3775087.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w4',
      title: 'Dynamic Walk',
      description: 'Walking pose with natural movement',
      imageUrl: 'https://images.pexels.com/photos/3756512/pexels-photo-3756512.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w5',
      title: 'Hand on Hip',
      description: 'Confident pose with hand on hip',
      imageUrl: 'https://images.pexels.com/photos/3775131/pexels-photo-3775131.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w6',
      title: 'Leaning Back',
      description: 'Relaxed leaning pose against wall',
      imageUrl: 'https://images.pexels.com/photos/3785082/pexels-photo-3785082.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w7',
      title: 'Over Shoulder',
      description: 'Looking back over shoulder pose',
      imageUrl: 'https://images.pexels.com/photos/3775146/pexels-photo-3775146.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w8',
      title: 'Arms Crossed',
      description: 'Confident pose with arms crossed',
      imageUrl: 'https://images.pexels.com/photos/3785074/pexels-photo-3785074.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w9',
      title: 'Hair Flip',
      description: 'Dynamic hair movement pose',
      imageUrl: 'https://images.pexels.com/photos/3756766/pexels-photo-3756766.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w10',
      title: 'Sitting Forward',
      description: 'Seated pose leaning forward',
      imageUrl: 'https://images.pexels.com/photos/3775118/pexels-photo-3775118.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w11',
      title: 'Looking Up',
      description: 'Pose with gaze directed upward',
      imageUrl: 'https://images.pexels.com/photos/3785083/pexels-photo-3785083.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w12',
      title: 'Close Portrait',
      description: 'Intimate close-up portrait pose',
      imageUrl: 'https://images.pexels.com/photos/3756514/pexels-photo-3756514.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w13',
      title: 'Full Length',
      description: 'Full body standing pose',
      imageUrl: 'https://images.pexels.com/photos/3785077/pexels-photo-3785077.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w14',
      title: 'Three Quarter',
      description: 'Angled three quarter pose',
      imageUrl: 'https://images.pexels.com/photos/3775142/pexels-photo-3775142.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w15',
      title: 'Hands in Pockets',
      description: 'Casual pose with hands in pockets',
      imageUrl: 'https://images.pexels.com/photos/3785076/pexels-photo-3785076.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w16',
      title: 'Against Wall',
      description: 'Leaning against wall pose',
      imageUrl: 'https://images.pexels.com/photos/3756547/pexels-photo-3756547.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w17',
      title: 'Playful Spin',
      description: 'Spinning or twirling pose',
      imageUrl: 'https://images.pexels.com/photos/3775134/pexels-photo-3775134.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w18',
      title: 'Chin on Hand',
      description: 'Thoughtful pose with chin resting on hand',
      imageUrl: 'https://images.pexels.com/photos/3785081/pexels-photo-3785081.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w19',
      title: 'Back View',
      description: 'Pose showing back view',
      imageUrl: 'https://images.pexels.com/photos/3756519/pexels-photo-3756519.jpeg',
      category: 'women',
      isFavorite: false,
    },
    {
      id: 'w20',
      title: 'Outdoor Natural',
      description: 'Natural outdoor standing pose',
      imageUrl: 'https://images.pexels.com/photos/3775155/pexels-photo-3775155.jpeg',
      category: 'women',
      isFavorite: false,
    },
  ],
  men: [
    {
      id: 'm1',
      title: 'Confident Stand',
      description: 'Strong standing pose with good posture',
      imageUrl: 'https://images.pexels.com/photos/3785104/pexels-photo-3785104.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm2',
      title: 'Arms Crossed',
      description: 'Authoritative pose with crossed arms',
      imageUrl: 'https://images.pexels.com/photos/3777568/pexels-photo-3777568.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm3',
      title: 'Casual Lean',
      description: 'Relaxed leaning pose',
      imageUrl: 'https://images.pexels.com/photos/3785103/pexels-photo-3785103.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm4',
      title: 'Hands in Pockets',
      description: 'Casual pose with hands in pockets',
      imageUrl: 'https://images.pexels.com/photos/3777931/pexels-photo-3777931.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm5',
      title: 'Side Profile',
      description: 'Strong side profile pose',
      imageUrl: 'https://images.pexels.com/photos/3785106/pexels-photo-3785106.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm6',
      title: 'Walking Forward',
      description: 'Dynamic walking pose',
      imageUrl: 'https://images.pexels.com/photos/3777622/pexels-photo-3777622.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm7',
      title: 'Seated Power',
      description: 'Confident seated pose',
      imageUrl: 'https://images.pexels.com/photos/3785095/pexels-photo-3785095.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm8',
      title: 'Looking Away',
      description: 'Contemplative pose looking to the side',
      imageUrl: 'https://images.pexels.com/photos/3777943/pexels-photo-3777943.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm9',
      title: 'Jacket Over Shoulder',
      description: 'Stylish pose with jacket over shoulder',
      imageUrl: 'https://images.pexels.com/photos/3785105/pexels-photo-3785105.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm10',
      title: 'Against Wall',
      description: 'Leaning against wall casually',
      imageUrl: 'https://images.pexels.com/photos/3777960/pexels-photo-3777960.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm11',
      title: 'Hands Behind Head',
      description: 'Relaxed pose with hands behind head',
      imageUrl: 'https://images.pexels.com/photos/3785102/pexels-photo-3785102.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm12',
      title: 'Close Portrait',
      description: 'Intense close-up portrait',
      imageUrl: 'https://images.pexels.com/photos/3777572/pexels-photo-3777572.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm13',
      title: 'Full Body Shot',
      description: 'Full length standing pose',
      imageUrl: 'https://images.pexels.com/photos/3785101/pexels-photo-3785101.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm14',
      title: 'Sitting Relaxed',
      description: 'Casual seated position',
      imageUrl: 'https://images.pexels.com/photos/3777923/pexels-photo-3777923.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm15',
      title: 'Looking Down',
      description: 'Thoughtful downward gaze',
      imageUrl: 'https://images.pexels.com/photos/3785100/pexels-photo-3785100.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm16',
      title: 'Hand on Chin',
      description: 'Contemplative pose with hand on chin',
      imageUrl: 'https://images.pexels.com/photos/3777617/pexels-photo-3777617.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm17',
      title: 'Athletic Stand',
      description: 'Strong athletic stance',
      imageUrl: 'https://images.pexels.com/photos/3785098/pexels-photo-3785098.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm18',
      title: 'Arms at Side',
      description: 'Natural pose with arms relaxed',
      imageUrl: 'https://images.pexels.com/photos/3777952/pexels-photo-3777952.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm19',
      title: 'Back View',
      description: 'Pose from behind',
      imageUrl: 'https://images.pexels.com/photos/3785097/pexels-photo-3785097.jpeg',
      category: 'men',
      isFavorite: false,
    },
    {
      id: 'm20',
      title: 'Outdoor Casual',
      description: 'Relaxed outdoor pose',
      imageUrl: 'https://images.pexels.com/photos/3777613/pexels-photo-3777613.jpeg',
      category: 'men',
      isFavorite: false,
    },
  ],
  kids: [
    {
      id: 'k1',
      title: 'Joyful Jump',
      description: 'Energetic jumping pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k2',
      title: 'Playful Run',
      description: 'Running and playing pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k3',
      title: 'Sitting Cross-Legged',
      description: 'Comfortable seated position',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k4',
      title: 'Happy Smile',
      description: 'Close-up smiling portrait',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k5',
      title: 'Arms Wide',
      description: 'Open arms joyful pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k6',
      title: 'Looking Up',
      description: 'Curious upward gaze',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k7',
      title: 'Hands on Face',
      description: 'Cute hands on face pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k8',
      title: 'Kneeling Down',
      description: 'Kneeling at play level',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k9',
      title: 'Lying Down',
      description: 'Relaxed lying pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k10',
      title: 'Standing Tall',
      description: 'Proud standing pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k11',
      title: 'Peeking Around',
      description: 'Playful peeking pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k12',
      title: 'On Tiptoes',
      description: 'Stretching on tiptoes',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k13',
      title: 'Blowing Kiss',
      description: 'Sweet blowing kiss pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k14',
      title: 'Spinning Around',
      description: 'Twirling and spinning',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k15',
      title: 'Holding Toy',
      description: 'Pose with favorite toy',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k16',
      title: 'Peace Sign',
      description: 'Fun peace sign pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k17',
      title: 'Superhero Stance',
      description: 'Confident superhero pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k18',
      title: 'Silly Face',
      description: 'Playful silly expression',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k19',
      title: 'Sitting Swing',
      description: 'Sitting on swing pose',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
    {
      id: 'k20',
      title: 'Group Play',
      description: 'Playing with friends',
      imageUrl: 'https://images.pexels.com/photos/1416736/pexels-photo-1416736.jpeg',
      category: 'kids',
      isFavorite: false,
    },
  ],
  couples: [
    {
      id: 'c1',
      title: 'Forehead Touch',
      description: 'Intimate forehead to forehead pose',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c2',
      title: 'Walking Together',
      description: 'Holding hands while walking',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c3',
      title: 'Back Hug',
      description: 'Embrace from behind',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c4',
      title: 'Nose to Nose',
      description: 'Playful nose touching',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c5',
      title: 'Dancing Close',
      description: 'Romantic dance pose',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c6',
      title: 'Sitting Together',
      description: 'Seated close together',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c7',
      title: 'Piggyback Ride',
      description: 'Fun piggyback pose',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c8',
      title: 'Looking at Each Other',
      description: 'Gazing into eyes',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c9',
      title: 'Hand in Hand',
      description: 'Holding hands facing camera',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c10',
      title: 'Leaning Together',
      description: 'Leaning against each other',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c11',
      title: 'Sitting on Lap',
      description: 'Romantic sitting pose',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c12',
      title: 'Side by Side',
      description: 'Standing side by side',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c13',
      title: 'Dipping Kiss',
      description: 'Romantic dip pose',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c14',
      title: 'Arms Around',
      description: 'Arms wrapped around each other',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c15',
      title: 'Lying Together',
      description: 'Lying down close together',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c16',
      title: 'Silhouette Kiss',
      description: 'Silhouette kissing pose',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c17',
      title: 'Looking Away Together',
      description: 'Both looking same direction',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c18',
      title: 'Playful Pose',
      description: 'Fun and playful together',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c19',
      title: 'Romantic Walk',
      description: 'Walking in romantic setting',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
    {
      id: 'c20',
      title: 'Sunset Embrace',
      description: 'Embracing during sunset',
      imageUrl: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg',
      category: 'couples',
      isFavorite: false,
    },
  ],
  dogs: [
    {
      id: 'd1',
      title: 'Sitting Pretty',
      description: 'Classic sitting pose',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd2',
      title: 'Happy Panting',
      description: 'Joyful panting expression',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd3',
      title: 'Lying Down',
      description: 'Relaxed lying position',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd4',
      title: 'Head Tilt',
      description: 'Curious head tilt',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd5',
      title: 'Running Action',
      description: 'Dynamic running shot',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd6',
      title: 'Paw Shake',
      description: 'Offering paw pose',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd7',
      title: 'Standing Alert',
      description: 'Alert standing position',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd8',
      title: 'Side Profile',
      description: 'Elegant side view',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd9',
      title: 'Playful Jump',
      description: 'Jumping in air',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd10',
      title: 'Close-up Face',
      description: 'Close portrait shot',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd11',
      title: 'With Toy',
      description: 'Holding favorite toy',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd12',
      title: 'Rolling Over',
      description: 'Playful rolling pose',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd13',
      title: 'Tongue Out',
      description: 'Happy tongue out',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd14',
      title: 'Catching Ball',
      description: 'Mid-catch action shot',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd15',
      title: 'Looking Up',
      description: 'Gazing upward pose',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd16',
      title: 'Ears Up',
      description: 'Alert with perked ears',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd17',
      title: 'Outdoor Portrait',
      description: 'Natural outdoor setting',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd18',
      title: 'Sleeping Peaceful',
      description: 'Peaceful sleeping pose',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd19',
      title: 'Walking Proud',
      description: 'Confident walking pose',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
    {
      id: 'd20',
      title: 'Group Shot',
      description: 'With other dogs',
      imageUrl: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg',
      category: 'dogs',
      isFavorite: false,
    },
  ],
  cats: [
    {
      id: 'cat1',
      title: 'Regal Sitting',
      description: 'Elegant sitting pose',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat2',
      title: 'Stretching Out',
      description: 'Full body stretch',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat3',
      title: 'Lying Cozy',
      description: 'Comfortable lying pose',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat4',
      title: 'Hunting Crouch',
      description: 'Ready to pounce',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat5',
      title: 'Playful Bat',
      description: 'Batting at toy',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat6',
      title: 'Looking Up',
      description: 'Curious upward gaze',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat7',
      title: 'Side Profile',
      description: 'Graceful side view',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat8',
      title: 'Grooming Pose',
      description: 'Mid-grooming position',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat9',
      title: 'Window Watching',
      description: 'Perched by window',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat10',
      title: 'Curled Up',
      description: 'Cozy curled position',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat11',
      title: 'Standing Alert',
      description: 'Alert standing pose',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat12',
      title: 'Close-up Face',
      description: 'Intimate facial portrait',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat13',
      title: 'Jumping Action',
      description: 'Mid-jump capture',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat14',
      title: 'Paw Tucked',
      description: 'Sitting with paws tucked',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat15',
      title: 'Back Arch',
      description: 'Arched back stretch',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat16',
      title: 'Sleepy Eyes',
      description: 'Drowsy relaxed look',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat17',
      title: 'Outdoor Explorer',
      description: 'Exploring outdoors',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat18',
      title: 'Belly Up',
      description: 'Playful belly exposure',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat19',
      title: 'Perched High',
      description: 'Sitting on high surface',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
    {
      id: 'cat20',
      title: 'Playing Together',
      description: 'With other cats',
      imageUrl: 'https://images.pexels.com/photos/2558605/pexels-photo-2558605.jpeg',
      category: 'cats',
      isFavorite: false,
    },
  ],
};
